# Generated by Django 5.1.13 on 2025-10-08 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais_origen', models.CharField(max_length=50)),
                ('año_fundacion', models.IntegerField(null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transmision', models.CharField(choices=[('AT', 'Automática'), ('MT', 'Manual')], default='MT', max_length=2)),
                ('fecha_fabricacion', models.DateField()),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.concesionario')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('puntos_fidelidad', models.FloatField(default=0.0)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_contratacion', models.DateField()),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.concesionario')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField()),
                ('kilometros', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('coste', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coches', models.ManyToManyField(to='AlphaAutos.coche')),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro', models.CharField(max_length=50)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duracion', models.IntegerField(help_text='Duración en meses')),
                ('coche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.coche')),
            ],
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('web', models.URLField(blank=True)),
                ('seguros', models.ManyToManyField(to='AlphaAutos.seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('experiencia', models.IntegerField(default=0)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.cliente')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.coche')),
            ],
        ),
    ]
