# Generated by Django 5.1.15 on 2025-12-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaAutos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_cliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='datos_cliente',
            name='comprador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.comprador'),
        ),
        migrations.AddField(
            model_name='venta',
            name='comprador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.comprador'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
