# Generated by Django 5.1.14 on 2025-11-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaAutos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aseguradora',
            name='web',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
