# Generated by Django 5.1.15 on 2025-12-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaAutos', '0002_remove_datos_cliente_cliente_remove_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
