# Generated by Django 5.1.14 on 2025-12-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaAutos', '0002_alter_aseguradora_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='año_fundacion',
            new_name='anio_fundacion',
        ),
    ]
