# Generated by Django 5.1.15 on 2025-12-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaAutos', '0003_comprador_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlphaAutos.comprador'),
        ),
    ]
