# Generated by Django 5.1.14 on 2025-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaAutos', '0003_rename_año_fundacion_marca_anio_fundacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='coches/'),
        ),
    ]
